"""add_time_entries_table

Revision ID: 6ca5964dcda6
Revises: cd4cebe6a23e
Create Date: 2025-12-27 15:59:15.967806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca5964dcda6'
down_revision: Union[str, Sequence[str], None] = 'cd4cebe6a23e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=128), nullable=False),
    sa.Column('clock_in', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('clock_out', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_employees_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_role'), table_name='employees')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_employees_role'), 'employees', ['role'], unique=False)
    op.create_index(op.f('ix_employees_name'), 'employees', ['name'], unique=False)
    op.drop_table('time_entries')
    # ### end Alembic commands ###
